import 'dart:async';
import 'dart:developer';
import 'dart:io';
import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

import 'package:google_fonts/google_fonts.dart';

import 'package:otp/otp.dart';
import 'package:qr_code_scanner/qr_code_scanner.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:tutorial_coach_mark/tutorial_coach_mark.dart';

// import 'package:url_launcher/url_launcher.dart';

import '../const/styleConst.dart';


class AuthenticatorApp {
  String appName;
  String secretKey;
  String label;

  late Timer timer;
  DateTime currentTime = DateTime.now();
  final StreamController<void> _timerController =
  StreamController<void>.broadcast();
  AuthenticatorApp({
    required this.appName,
    required this.secretKey,
    required this.label,

  }) {

    timer = Timer.periodic(Duration(seconds: 1), (timer) {
      if (!_timerController.isClosed) {
        _timerController.add(null);
      }
    });
  }

  Stream<void> get timerStream => _timerController.stream;
  void dispose() {
    _timerController.close();
  }
}

class ProfilePage extends StatefulWidget {
  final AuthenticatorApp app;

  ProfilePage({required this.app});

  @override
  State<ProfilePage> createState() => _ProfilePageState();
}

class _ProfilePageState extends State<ProfilePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.app.appName),
        centerTitle: true,
        backgroundColor: appBarColor,
        automaticallyImplyLeading: false,
        elevation: 0,
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          Container(
            margin: EdgeInsets.only(bottom: 20.0),
            alignment: Alignment.topCenter,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(5.0),
                topRight: Radius.circular(5.0),
                bottomRight: Radius.circular(0.0),
                bottomLeft: Radius.circular(0.0),
              ),
              color: Colors.grey.shade300,
            ),
            height: 250.0,
            child: Center(
              child: Image.asset('assets/logo.png', height: 200),
            ),
          ),
          Card(
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                      children: [
                        Icon(
                          FontAwesomeIcons.checkCircle,
                          color: appBarColor,
                        ),
                        Column(
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'One-time password enabled',
                              style: TextStyle(
                                fontSize: 16,
                                fontWeight: FontWeight.bold,
                                color: Colors.black,
                              ),
                            ),
                            Container(
                              width: 300,
                              child: Text(
                                'You can use the one-time password codes generated by this app to verify sign-ins',
                                style: TextStyle(
                                  fontSize: 14,
                                  color: Colors.black,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                    SizedBox(
                      height: 10,
                    ),
                    Divider(),
                    SizedBox(
                      height: 10,
                    ),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        StreamBuilder<void>(
                          stream: widget.app.timerStream,
                          builder: (context, snapshot) {
                            double progress =
                                widget.app.currentTime.second % 30 / 30.0;
                            return Stack(alignment: Alignment.center, children: [
                              CircularProgressIndicator(
                                backgroundColor: Colors.grey.shade200,
                                value: progress,
                                valueColor:
                                AlwaysStoppedAnimation<Color>(appBarColor),
                              ),
                              Text(
                                '${(30 - widget.app.currentTime.second % 30)}',
                                style: TextStyle(
                                  fontSize: 14,
                                  fontStyle: FontStyle.italic,
                                  color: appBarColor,
                                ),
                              )
                            ]);
                          },
                        ),
                        SizedBox(
                          width: 10,
                        ),
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'One-time password code',
                              style: TextStyle(
                                fontSize: 16,
                                color: Colors.black,
                              ),
                            ),
                            StreamBuilder<void>(
                              stream: widget.app.timerStream,
                              builder: (context, snapshot) {
                                return Text(
                                  _generateTOTP(widget.app),
                                  style: TextStyle(
                                    fontSize: 45,
                                    fontWeight: FontWeight.bold,
                                    color: appBarColor,
                                  ),
                                );
                              },
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              )),
        ],
      ),
    );
  }

  String _generateTOTP(AuthenticatorApp app) {
    String totpValue = OTP.generateTOTPCodeString(
      app.secretKey,
      DateTime.now().millisecondsSinceEpoch,
      isGoogle: true,
      algorithm: Algorithm.SHA1,
    );
    return totpValue;
  }
}

class Dashboard extends StatefulWidget {
  const Dashboard({Key? key}) : super(key: key);

  @override
  State<Dashboard> createState() => _DashboardState();
}

class _DashboardState extends State<Dashboard> {
  List<TargetFocus> targets = [];
  GlobalKey _qrKeyTutorial = GlobalKey();
  GlobalKey _iconKey = GlobalKey();
  GlobalKey _timeKey = GlobalKey();
  late TutorialCoachMark _tutorialCoachMark;
  List<AuthenticatorApp> authenticatorApps = [];
  List<String> appNames=[];
  // LatLng? currentLocation;
  int radius=0;
  double fenceLat =0.0;
  double fenceLng = 0.0;
  bool? outside;
  String status = 'inside';

  // Future<void> _getCurrentLocation() async {
  //   SharedPreferences preferences = await SharedPreferences.getInstance();
  //
  //   LocationPermission locationPermission = await Geolocator.checkPermission();
  //   if (locationPermission == LocationPermission.denied) {
  //     locationPermission = await Geolocator.requestPermission();
  //     if (locationPermission == LocationPermission.deniedForever) {
  //
  //     }
  //   }
  //
  //   if (locationPermission == LocationPermission.whileInUse ||
  //       locationPermission == LocationPermission.always) {
  //     try {
  //       Position position = await Geolocator.getCurrentPosition(
  //         desiredAccuracy: LocationAccuracy.bestForNavigation,
  //       );
  //       currentLocation = LatLng(position.latitude, position.longitude);
  //       authenticatorApps.isNotEmpty?checkFencingWithAuthDone():log('empty');
  //       log("current lat${position.latitude}");
  //       log("current lang${position.longitude}");
  //       // if(radius!=0){
  //       //   log("current lat:"+ position.latitude.toString());
  //       //   log("current lng:"+ position.longitude.toString());
  //       //   log("fence lat:"+ fenceLat.toString());
  //       //   log("fence lng:"+ fenceLng.toString());
  //       //   log("radius:"+ radius.toString());
  //       //   double distanceInMeters = Geolocator.distanceBetween(
  //       //     position.latitude,
  //       //     position.longitude,
  //       //     fenceLat,
  //       //     fenceLng,
  //       //   );
  //       //
  //       //   if (distanceInMeters <= radius!) {
  //       //     setState(() {
  //       //       currentLocation = LatLng(position.latitude, position.longitude);
  //       //       outside=false;
  //       //       // preferences.setDouble("lat", position.latitude);
  //       //       // preferences.setDouble("lng", position.longitude);
  //       //     });
  //       //   } else {
  //       //     setState(() {
  //       //       outside=true;
  //       //       _showScanner=false;
  //       //     });
  //       //     log("outside");
  //       //     double distanceInKm = distanceInMeters / 1000;
  //       //     String formattedDistance = distanceInKm.toStringAsFixed(2);
  //       //     ScaffoldMessenger.of(context).showSnackBar(
  //       //         SnackBar(content: Text("You are outside of the radius: you are $formattedDistance km away.")));
  //       //
  //       //   }
  //       // }
  //
  //
  //
  //     } catch (e) {
  //       showDialog(
  //         context: context,
  //         builder: (context) => AlertDialog(
  //           title: const Text('Location Service Disabled Exception'),
  //           content: const Text('Please enable location services to use this app.'),
  //           actions: [
  //             TextButton(
  //               onPressed: () async{
  //                 locationPermission = await Geolocator.requestPermission();
  //               },
  //               child: const Text('OK'),
  //             ),
  //           ],
  //         ),
  //       );
  //     }
  //   } else {
  //     showDialog(
  //       context: context,
  //       builder: (context) => AlertDialog(
  //         title: const Text('Location Permission Required'),
  //         content: const Text('This app requires access to your location to function properly.'),
  //         actions: [
  //           TextButton(
  //             onPressed: () async{
  //               Navigator.pop(context);
  //               locationPermission = await Geolocator.requestPermission();
  //             },
  //             child: const Text('OK'),
  //           ),
  //         ],
  //       ),
  //     );
  //   }
  // }

  // void checkFencing(double fenceLat,fenceLng,int radiusFromUrl) async{
  //   SharedPreferences prefs = await SharedPreferences.getInstance();
  //
  //   if(radiusFromUrl!=0){
  //     log("current lat:"+   currentLocation!.latitude.toString());
  //     log("current lng:"+ currentLocation!.longitude.toString());
  //     log("fence lat:"+ fenceLat.toString());
  //     log("fence lng:"+ fenceLng.toString());
  //     log("radius:"+ radiusFromUrl.toString());
  //     double distanceInMeters = Geolocator.distanceBetween(
  //       currentLocation!.latitude,
  //       currentLocation!.longitude,
  //       fenceLat,
  //       fenceLng,
  //     );
  //     prefs.setDouble('fenceLat', fenceLat);
  //     prefs.setDouble('fenceLng', fenceLng);
  //     prefs.setInt('radius', radiusFromUrl);
  //
  //     if (distanceInMeters <= radiusFromUrl!) {
  //       log("inside");
  //       setState(() {
  //         status = 'inside';
  //         // currentLocation = LatLng(currentLocation!.latitude, currentLocation!.longitude);
  //         outside=false;
  //         // preferences.setDouble("lat", position.latitude);
  //         // preferences.setDouble("lng", position.longitude);
  //       });
  //     } else {
  //       setState(() {
  //         outside=true;
  //         _showScanner=false;
  //       });
  //       status = 'outside';
  //       log("outside");
  //       double distanceInKm = distanceInMeters / 1000;
  //       String formattedDistance = distanceInKm.toStringAsFixed(2);
  //       ScaffoldMessenger.of(context).showSnackBar(
  //           SnackBar(content: Text("You are outside of the radius: you are $formattedDistance km away.")));
  //
  //     }
  //   }
  // }
  // void checkFencingWithAuthDone() async{
  //   SharedPreferences prefs = await SharedPreferences.getInstance();
  //   double lat= prefs.getDouble('fenceLat')!;
  //   double lng=  prefs.getDouble('fenceLng')!;
  //   int radius= prefs.getInt('radius')!;
  //   if(radius!=0){
  //     log("current lat:"+   currentLocation!.latitude.toString());
  //     log("current lng:"+ currentLocation!.longitude.toString());
  //     log("fence lat:"+ lat.toString());
  //     log("fence lng:"+ lng.toString());
  //     log("radius:"+ radius.toString());
  //     double distanceInMeters = Geolocator.distanceBetween(
  //       currentLocation!.latitude,
  //       currentLocation!.longitude,
  //       lat,
  //       lng,
  //     );
  //
  //
  //     if (distanceInMeters <= radius!) {
  //       log("inside");
  //       setState(() {
  //         status = 'inside';
  //         // currentLocation = LatLng(currentLocation!.latitude, currentLocation!.longitude);
  //         outside=false;
  //         // preferences.setDouble("lat", position.latitude);
  //         // preferences.setDouble("lng", position.longitude);
  //       });
  //     } else {
  //       setState(() {
  //         outside=true;
  //         _showScanner=false;
  //       });
  //       status = 'outside';
  //       log("outside");
  //       double distanceInKm = distanceInMeters / 1000;
  //       String formattedDistance = distanceInKm.toStringAsFixed(2);
  //       ScaffoldMessenger.of(context).showSnackBar(
  //           SnackBar(content: Text("You are outside of the radius: you are $formattedDistance km away.")));
  //
  //     }
  //   }
  // }




  int _currentTargetIndex = 0;
  // void _showTutorial() async{
  //   SharedPreferences preferences = await SharedPreferences.getInstance();
  //   WidgetsBinding.instance.addPostFrameCallback((_) {
  //     _tutorialCoachMark = TutorialCoachMark(
  //       targets: targets,
  //       colorShadow: Colors.black.withOpacity(0.7),
  //       textSkip: "Skip",
  //       onFinish: () {
  //         preferences.setString("tutorialDone", "true");
  //         print("Tutorial finished");
  //       },
  //       onClickTarget: (target) {
  //         _currentTargetIndex++;
  //         if (_currentTargetIndex < targets.length) {
  //           _tutorialCoachMark.goTo(_currentTargetIndex);
  //         } else {
  //           _tutorialCoachMark.finish();
  //         }
  //       },
  //
  //     );
  //     _tutorialCoachMark.show(context: context);
  //   });
  // }

  @override
  void initState() {
    super.initState();
    _getLocalData();
    // if(tutorialDone==false){
    //   _createTargets();
    //   Future.delayed(Duration.zero, _showTutorial);
    // }else{}

    // _showTutorial();

    // _getCurrentLocation();
    log(appNames.toString());

    // WidgetsBinding.instance.addPostFrameCallback((_) {
    //   _showBottomSheet(context);
    // });
  }
  final GlobalKey _qrKey = GlobalKey(debugLabel: 'QR');
  String? tutorialDone="false";
  Future<void> _getLocalData() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    List<String>? appNames = prefs.getStringList('appNames');
    List<String>? secretKeys = prefs.getStringList('secretKeys');
    List<String>? label = prefs.getStringList('label');
    tutorialDone=prefs.getString("tutorialDone")??"false";
    log("done?"+tutorialDone.toString());

    if (appNames != null && secretKeys != null&&label!=null) {
      for (int i = 0; i < appNames.length; i++) {
        AuthenticatorApp app = AuthenticatorApp(
            appName: appNames[i],
            secretKey: secretKeys[i],
            label: label[i]
        );
        if(authenticatorApps.isEmpty){
          authenticatorApps.add(app);
        }else{
          log("delete first");
        }
        startTimer(app);
      }
      setState(() {

      });
    }
  }

  void saveApp(String appName, String secretKey,String labelFromUrl) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    List<String> appNames = prefs.getStringList('appNames') ?? [];
    List<String> secretKeys = prefs.getStringList('secretKeys') ?? [];
    List<String> label = prefs.getStringList('label') ?? [];
    if(appNames.isEmpty){
      appNames.add(appName);
      secretKeys.add(secretKey);
      label.add(labelFromUrl);
    }else{
    }
    await prefs.setStringList('appNames', appNames);
    await prefs.setStringList('secretKeys', secretKeys);
    await prefs.setStringList('label', label);
    AuthenticatorApp app = AuthenticatorApp(
        appName: appName,
        secretKey: secretKey,
        label:labelFromUrl
    );
    if(authenticatorApps.isEmpty){
      authenticatorApps.add(app);
      if(tutorialDone=="false"){
        // _createTargets();
        // Future.delayed(Duration.zero, _showTutorial);
      }else{}

    }else{
    }

    startTimer(app);
    setState(() {});
  }
  String generateTOTP(String secretKey) {
    String totpValue = OTP.generateTOTPCodeString(
      secretKey,
      DateTime.now().millisecondsSinceEpoch,
      isGoogle: true,
      algorithm: Algorithm.SHA1,
    );
    return totpValue;
  }

  bool _showScanner = false;
  late QRViewController _controller;


  void startTimer(AuthenticatorApp app) {
    app.timer = Timer.periodic(Duration(seconds: 1), (timer) {
      app.currentTime = DateTime.now();
      if (!app._timerController.isClosed) {
        app._timerController.add(null);
      }
    });

  }

  void startAllTimers() {
    for (var app in authenticatorApps) {
      startTimer(app);
    }
  }
  void _deleteApp(int index) async {
    setState(() {
      authenticatorApps[index].dispose();
      authenticatorApps.removeAt(index);
    });

    SharedPreferences prefs = await SharedPreferences.getInstance();
    List<String> appNames = prefs.getStringList('appNames')!..removeAt(index);
    List<String> secretKeys = prefs.getStringList('secretKeys')!..removeAt(index);
    await prefs.setStringList('appNames', appNames);
    await prefs.setStringList('secretKeys', secretKeys);
  }
  double _elevation = 10.0;
  // _launchURL() async {
  //   final Uri _url = Uri.parse('https://sooritechnology.com');
  //   if (!await launchUrl(_url)) {
  //     log(_url.toString());
  //     throw Exception('Could not launch $_url');
  //   }
  // }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor:appBarColor,
      appBar: PreferredSize(
        preferredSize: Size.fromHeight(kToolbarHeight),
        child: Stack(
          children: [
            ClipRect(
              child: BackdropFilter(
                filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
                child: Container(
                  color: Colors.transparent,
                ),
              ),
            ),
            AppBar(
              title: Text(
                'Aristi Authenticator',
                style: GoogleFonts.rajdhani(
                    textStyle: Theme.of(context).textTheme.displayLarge,
                    fontSize: 24,
                    fontWeight: FontWeight.w700,
                    color: Colors.white,
                    letterSpacing: 0
                ),  ),
              leading: Platform.isIOS?Visibility(
                visible: _showScanner,
                child: GestureDetector(
                  onTap: () {
                    setState(() {
                      _showScanner = false;
                    });
                  },
                  child: Icon(Icons.arrow_back_ios,color: Colors.white,),
                ),
              ):Text(""),
              elevation: 0,
              backgroundColor: appBarColor,
              centerTitle: true,
              actions: [
                authenticatorApps.isEmpty?Text(""): IconButton(
                  key: _qrKeyTutorial,
                  icon: Icon(Icons.qr_code_2, color: Colors.white,size: 35,),
                  onPressed: () {
                    setState(() {
                      _showScanner = !_showScanner;
                    });
                  },
                ),
                SizedBox(width: 10,)
              ],
            ),
          ],
        ),
      ),


      body: _showScanner ? _buildScanner() :
      authenticatorApps.isEmpty?Align(
        alignment: Alignment.bottomCenter,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.start,
          children: [

            Padding(
              padding: const EdgeInsets.only(top: 150.0),
              child: Material(
                color: Colors.white.withOpacity(1),
                elevation: _elevation,
                borderRadius: BorderRadius.circular(20),
                child: InkWell(
                  onTap: () {
                    outside==true?
                    ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(content: Text("You are outside the desired location."))):
                    setState(() {
                      _showScanner = !_showScanner;
                      _elevation = _elevation == 10.0 ? 4.0 : 10.0;
                    });
                  },
                  borderRadius: BorderRadius.circular(20),
                  splashColor: Colors.black.withOpacity(0.1),
                  highlightColor: Colors.black.withOpacity(0.1),
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Icon(
                      Icons.qr_code_2,
                      size: 250,
                      color: appBarColor,
                    ),
                  ),
                ),
              ),
            ),

            SizedBox(height: 50,),
            Text(
              "Please tap on the Qr to continue.",
              style: GoogleFonts.rajdhani(
                textStyle: Theme.of(context).textTheme.displayLarge,
                fontSize: 20,
                fontWeight: FontWeight.w700,
                color: Colors.white,
                letterSpacing: 0,
              ),
            ),
            Spacer(),
            Padding(
              padding: const EdgeInsets.only(bottom: 15.0),
              child: GestureDetector(
                onTap: (){
                  // _launchURL();
                },
                child: Column(
                  children: [
                    Text(
                      "Developed and maintained by",
                      style: GoogleFonts.rajdhani(
                        textStyle: Theme.of(context).textTheme.displayLarge,
                        fontSize: 9,
                        fontWeight: FontWeight.w700,
                        color: Colors.white,
                        letterSpacing: 0,
                      ),
                    ),
                    Text(
                      "Soori Technology Pvt. Ltd",
                      style: GoogleFonts.rajdhani(
                        textStyle: Theme.of(context).textTheme.displayLarge,
                        fontSize: 12,
                        fontWeight: FontWeight.w700,
                        color: Colors.white,
                        letterSpacing: 0,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      )
          : ListView.builder(
        itemCount: authenticatorApps.length,
        itemBuilder: (context, index) {
          return GestureDetector(
            onTap: () {
              // Navigator.push(
              //   context,
              //   MaterialPageRoute(
              //     builder: (context) =>
              //         ProfilePage(app: authenticatorApps[index]),
              //   ),
              // );
            },
            child: Card(
              color: appBarColor,
              child: ListTile(
                subtitle: StreamBuilder<void>(
                  stream: authenticatorApps[index].timerStream,
                  builder: (context, snapshot) {
                    appNames.add(authenticatorApps[index].appName);
                    return Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Container(
                          height: MediaQuery.of(context).size.height*0.9 ,
                          width: MediaQuery.of(context).size.width,
                          child: Column(
                            children: [
                              Expanded(
                                child: Column(
                                  children: [
                                    Stack(
                                      alignment: Alignment.center,
                                      children: [
                                        Padding(
                                          padding: const EdgeInsets.only(top: 30.0),
                                          child: Stack(
                                            alignment: Alignment.center,
                                            children: [
                                              Container(
                                                height: 200,
                                                width: 200,
                                                child: CircularProgressIndicator(
                                                  strokeWidth: 4,
                                                  backgroundColor: Colors.white,
                                                  value: authenticatorApps.isEmpty
                                                      ? 0.0
                                                      : authenticatorApps[0]
                                                      .currentTime.second %
                                                      30 /
                                                      30.0,
                                                  valueColor: AlwaysStoppedAnimation<Color>(
                                                      appBarColor),
                                                ),
                                              ),
                                              Container(
                                                height: 180,
                                                width: 180, // Ensure the container is square for a perfect circle
                                                decoration: BoxDecoration(
                                                  color: Colors.white, // White background
                                                  shape: BoxShape.circle, // Circular shape
                                                ),
                                                child: Padding(
                                                  padding: const EdgeInsets.all(50.0), // Adjust padding to center the image
                                                  child: Image.asset(
                                                    'assets/favicon1.png',
                                                    height: 20, // Image size smaller than the container
                                                  ),
                                                ),
                                              )


                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                    status=='inside'?  Column(
                                      children: [
                                        SizedBox(height: 30), // Reduced the gap
                                        Text(
                                          authenticatorApps.isEmpty
                                              ? "N\A"
                                              : '${30 - authenticatorApps[0].currentTime.second % 30}',
                                          style: GoogleFonts.rajdhani(
                                              textStyle: Theme.of(context).textTheme.displayLarge,
                                              fontSize: 50,
                                              fontWeight: FontWeight.w700,
                                              color: Colors.white,
                                              letterSpacing: 0
                                          ),
                                          key: _timeKey,
                                        ),
                                        Text(
                                          'Seconds Remaining',
                                          style: GoogleFonts.rajdhani(
                                              textStyle: Theme.of(context).textTheme.displayLarge,
                                              fontSize: 20,
                                              fontWeight: FontWeight.w700,
                                              color: Colors.white,
                                              letterSpacing: 0
                                          ),
                                        ),
                                      ],
                                    ):Text("Location Tracking Enabled"),
                                  ],
                                ),
                              ),

                              Container(
                                height: MediaQuery.of(context).size.height/2.7,
                                width: double.infinity,

                                decoration: BoxDecoration(
                                  color: Colors.white,
                                  borderRadius: BorderRadius.vertical(
                                    top: Radius.circular(24), // Rounded top corners
                                  ),
                                  boxShadow: [
                                    BoxShadow(
                                      color: Colors.black26,
                                      blurRadius: 16,
                                      offset: Offset(0, -4),
                                    ),
                                  ],
                                ),
                                padding: const EdgeInsets.symmetric(vertical:20.0, horizontal: 30.0),
                                child: Column(
                                  children: [
                                    Row(
                                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                      children: [
                                        Column(
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            Text(
                                              authenticatorApps[index].appName,
                                              style: GoogleFonts.rajdhani(
                                                  textStyle: Theme.of(context).textTheme.displayLarge,
                                                  fontSize: 24,
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: 0
                                              ), ),
                                            Text(
                                              authenticatorApps[index].label.toUpperCase(),
                                              style: GoogleFonts.rajdhani(
                                                  textStyle: Theme.of(context).textTheme.displayLarge,
                                                  fontSize: 16,
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: 0
                                              ), ),
                                          ],
                                        ),
                                        IconButton(
                                          key: _iconKey,
                                          icon: const Icon(Icons.delete_outline,color: Colors.black,size: 30,),
                                          onPressed: () {
                                            showDialog(
                                              context: context,
                                              builder: (BuildContext context) {
                                                return AlertDialog(
                                                  title: Text("Confirm Deletion"),
                                                  content: Text("Are you sure you want to delete this item?"),
                                                  actions: [
                                                    TextButton(
                                                      onPressed: () {
                                                        Navigator.of(context).pop(); // Close the dialog
                                                      },
                                                      child: Text("Cancel",style: TextStyle(color: appBarColor),),
                                                    ),
                                                    TextButton(
                                                      onPressed: () async{
                                                        SharedPreferences prefs = await SharedPreferences.getInstance();

                                                        _deleteApp(index);
                                                        prefs.setString("tutorialDone", "false");

                                                        Navigator.of(context).pop();
                                                      }, child:Text("Delete",style: TextStyle(color: appBarColor),),
                                                    ),
                                                  ],
                                                );
                                              },
                                            );
                                          },
                                        ),

                                      ],
                                    ),
                                    SizedBox(height:10),
                                    status=='inside'?  Text(
                                      generateTOTP(authenticatorApps[index].secretKey),
                                      style: GoogleFonts.rajdhani(
                                          textStyle: Theme.of(context).textTheme.displayLarge,
                                          fontSize: 70,
                                          fontWeight: FontWeight.w700,
                                          letterSpacing: 5
                                      ),  ):Column(
                                      crossAxisAlignment: CrossAxisAlignment.center,

                                      children: [
                                        Text(
                                          'Oops!',
                                          style: GoogleFonts.rajdhani(
                                              textStyle: Theme.of(context).textTheme.displayLarge,
                                              fontSize: 30,
                                              fontWeight: FontWeight.w700,
                                              color: appBarColor,
                                              letterSpacing: 0
                                          ),  ),
                                        Text(
                                          'It looks you are not currently in \n         a branch location',
                                          style: GoogleFonts.rajdhani(
                                              textStyle: Theme.of(context).textTheme.displayLarge,
                                              fontSize: 12,
                                              fontWeight: FontWeight.w700,

                                              letterSpacing: 0
                                          ),  )
                                      ],
                                    ),
                                    SizedBox(height: 20),
                                    GestureDetector(
                                      onTap: (){
                                        // _launchURL();
                                      },
                                      child: Column(
                                        children: [
                                          Text(
                                            "Developed and maintained by",
                                            style: GoogleFonts.rajdhani(
                                              textStyle: Theme.of(context).textTheme.displayLarge,
                                              fontSize: 9,
                                              fontWeight: FontWeight.w700,
                                              color: Colors.black,
                                              letterSpacing: 0,
                                            ),
                                          ),
                                          Text(
                                            "Soori Technology Pvt. Ltd",
                                            style: GoogleFonts.rajdhani(
                                              textStyle: Theme.of(context).textTheme.displayLarge,
                                              fontSize: 12,
                                              fontWeight: FontWeight.w700,
                                              color: Colors.black,
                                              letterSpacing: 0,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    SizedBox(height: 20),

                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    );
                  },
                ),
              ),
            ),
          );
        },
      ),



    );
  }

  Widget _buildScanner() {
    return WillPopScope(
      onWillPop: () async {
        setState(() {
          _showScanner = false;
        });
        return false;
      },
      child: Stack(
        children: [
          BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
            child: Container(
              child: QRView(
                key: _qrKey,
                onQRViewCreated: _onQRViewCreated,
              ),
            ),
          ),
          Center(
            child: ClipRect(
              child: Container(
                height: MediaQuery.of(context).size.width * 0.6,
                width: MediaQuery.of(context).size.width * 0.6,
                decoration: BoxDecoration(
                  border: Border.all(
                    color: appBarColor,
                    width: 5,
                  ),
                  borderRadius: BorderRadius.circular(20),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
  void _onQRViewCreated(QRViewController controller) {
    _controller = controller;
    _controller.scannedDataStream.listen((scanData) {
      _handleScanResult(scanData.code!);
    });
  }
  void _handleScanResult(String code) {
    String barcodeScanRes;
    try {

      barcodeScanRes = code;
      Uri uri = Uri.parse('otpauth://'+barcodeScanRes);


      double lat = double.parse(uri.queryParameters['lat']!) ?? 0.0;
      double lng = double.parse(uri.queryParameters['lng']!) ?? 0.0;
      int radius1 = int.parse(uri.queryParameters['radius']!) ?? 0;
      String isEnabled = uri.queryParameters['isEnabled']!?? 'false';


      log("enabled"+isEnabled);
      if(isEnabled=='true'){
        // _getCurrentLocation();
        // checkFencing(lat,lng,radius1);
      }else{}

      log('otpauth://'+barcodeScanRes);
      // log("status"+status!);

      if(isEnabled == 'true'&&status=='inside'){
        String scannedSecretKey = uri.queryParameters['secret'] ?? '';
        String appName = uri.queryParameters['issuer'] ?? '';
        String lable = uri.queryParameters['label'] ?? '';
        if (scannedSecretKey.isNotEmpty) {
          bool hasExistingApp = authenticatorApps.any((app) => app.appName == appName);
          if (hasExistingApp) {
            int indexToRemove = authenticatorApps.indexWhere((app) => app.appName == appName);
            _deleteApp(indexToRemove);
          }
          saveApp(appName, scannedSecretKey,lable);
        }
      }else{
        String scannedSecretKey = uri.queryParameters['secret'] ?? '';
        String appName = uri.queryParameters['issuer'] ?? '';
        String lable = uri.queryParameters['label'] ?? '';
        if (scannedSecretKey.isNotEmpty) {
          bool hasExistingApp = authenticatorApps.any((app) => app.appName == appName);
          if (hasExistingApp) {
            int indexToRemove = authenticatorApps.indexWhere((app) => app.appName == appName);
            _deleteApp(indexToRemove);
          }
          saveApp(appName, scannedSecretKey,lable);

        }
        // ScaffoldMessenger.of(context).showSnackBar(
        //           SnackBar(content: Text("You are outside of the radius.")));
      }

      setState(() {
        _showScanner=false;
      });

    } on FormatException catch (_) {

    }

  }


  @override
  void dispose() {
    for (var app in authenticatorApps) {
      app.dispose();
    }
    if (_controller != null) {
      _controller.dispose(); // Dispose the controller to avoid memory leaks
    }
    super.dispose();
  }
}


///otpauth://